### ISSUE TITLE
Mac ARM (Apple Silicon)-native build

### ISSUE THREAD

**Issue by ajmas** [MaddTheSane/Boxer#13]
Originally opened here: https://github.com/alunbestor/Boxer/issues/109

Now that Apple Silicon (ARM on Mac) systems are beginning to ship, please create an updated native build for these systems on Mac OS 11.

My comment:

Maybe the starting point would be [QEMU](https://www.qemu.org/) or [box86](https://github.com/ptitSeb/box86) which people have gotten to run on the Raspberry Pi:

 - https://www.raspberrypi.org/forums/viewtopic.php?t=246886
 - https://opensource.com/article/18/3/can-you-run-dos-raspberry-pi
 - https://magpi.raspberrypi.org/articles/build-a-dos-emulation-system

  Next, would be getting access to an M1 based Mac, physically or remote. 

On the other hand given no source updates in 4 years, I am not too confident.

**Comment by MaddTheSane** [comment]
Recent builds are compiling and running under Apple Silicon natively. You can thank @stuartcarnie for that.

**Comment by designbyadrian** [comment]
> Recent builds are compiling and running under Apple Silicon natively. You can thank @stuartcarnie for that.

Are these builds different from the executable linked from the [homepage](http://boxerapp.com)? This one doesn't launch on macOS 12.0.1. Is it due to the 64-bit requirement?

**Comment by ajmas** [comment]
> > Recent builds are compiling and running under Apple Silicon natively. You can thank @stuartcarnie for that.
> 
> Are these builds different from the executable linked from the [homepage](http://boxerapp.com)? This one doesn't launch on macOS 12.0.1. Is it due to the 64-bit requirement?

Best open a new ticket for launch errors. Be sure to include details about your environment and any logs that may seem relevant in /var/log/system.log 

All macOS releases have been 64-bit for at least 5 years.
