### ISSUE TITLE
Problems building Boxer

### ISSUE THREAD

**Issue by mintho** [MaddTheSane/Boxer#15]
Sorry for being a n00b, but in the absence of binaries, I tried my luck with building this thing.

I could already troubleshoot a little bit by myself, but now I get the following errors when trying to build:
`/Users/mintho/XCode/Boxer/Vendor/OpenEmuShaders/3rdparty/SPIRV-Tools/source/opcode.cpp:340:10: use of undeclared identifier 'SpvOpTypeRayQueryProvisionalKHR'; did you mean 'SpvCapabilityRayQueryProvisionalKHR'?`
And
`Command CompileSwift failed with a nonzero exit code`

Can somebody lead me into the right direction please? That would be very much appreciated

**Comment by MaddTheSane** [comment]
[OpenEmuShaders](https://github.com/OpenEmu/OpenEmu-Shaders) needs to be updated.
