### ISSUE TITLE
Boxer 2.0.0 opens parent folder to games folder; not actual games folder

### ISSUE THREAD

**Issue by influx3k** [MaddTheSane/Boxer#27]
When setting "When Boxer starts" to "Open my games folder in Finder" Boxer opens the parent folder to the games folder, not the actual games folder.  This requires one more step to actually go into the games folder.  Please fix.

**Comment by rgs1024** [comment]
Hi,

A possible fix will be using `[NSWorkspace selectFile: inFileViewerRootedAtPath:]` instead `[NSWorkspace activateFileViewerSelectingURLs:]`.

Replacing:

```
if (safeURLs.count)
    [ws activateFileViewerSelectingURLs: safeURLs];
```

at `- (BOOL) revealURLsInFinder: (NSArray *)URLs` in `BXBaseAppController.m` for:

```
for (NSURL *url in safeURLs)
{
    if (url != nil)
    {
        NSString *file = (url.isDirectory ? nil : url.path);
        NSString *path = (url.isDirectory ? url.path : [url URLByDeletingLastPathComponent].path);
                
        [ws selectFile: file inFileViewerRootedAtPath: path];
    }
}
```

**Comment by influx3k** [comment]
Is this ever going to get fixed?
