### ISSUE TITLE
Floppy IMG Drive Support

### ISSUE THREAD

**Issue by tcjennings** [MaddTheSane/Boxer#28]
Was support for floppy disk images removed? 

With Version 2.0.0-alpha | build 2.0.0-alpha+20191017 (the only release I've been able to download and/or build) there is no opportunity to mount IMG disk images (they are greyed-out in the Finder selector and cannot be drag/dropped into the Import window.

**Comment by MaddTheSane** [comment]
Files ending with .img should be selectable.
I'll look into it…

**Comment by MaddTheSane** [comment]
This should be fixed by 7a3b8eb94d719bbca1f2f441a560e15648ba7b0d.
