### ISSUE TITLE
Left Control causes Boxer to crash

### ISSUE THREAD

**Issue by kyods** [MaddTheSane/Boxer#29]
Pressing the left control key in a game causes Boxer to crash. Sometimes it takes just one press, sometimes several presses. Tested with Witchaven, Hexen, Blackthorne and Settlers 2 (the last two don't even use the left control key).

EDIT: It seems the control key on its own is harmless. Crashes occur when the control key is pressed while simultaneously pressing the arrow keys. Some weird collision with the Mission Control shortcuts?

Mac Mini M1, using the build available in the Releases section.

**Comment by MaddTheSane** [comment]
I fixed the bug in commit 4531fd25557b7d4096b1718a07bffe03c4ab30ed.
