### ISSUE TITLE
Latest binary files

### ISSUE THREAD

**Issue by fedekrum** [MaddTheSane/Boxer#3]
Where can I get your bin files?
Is there a place where to download the latest built app?
Thanks for your effort !!

My own answer one year later:
Looks like if you want to be at the edge you must look for them at
[https://boxer.thec0de.com/](https://boxer.thec0de.com/)

**Comment by MaddTheSane** [comment]
The best stable build from https://github.com/alunbestor/Boxer/issues/76 would probably be this version https://www.dropbox.com/s/nwvw2q9kwxxbd2l/maddsv2%2012.07.2019.zip?dl=0
Note that I've hit a bit of a roadblock in regards to migrating away from `glDrawArrays` to `glCallList`. Mainly, I'm not familiar with OpenGL to migrate/fix it.

**Comment by augmentedfourth** [comment]
My USB Gravis Gamepad Pro isn't working with this build. The buttons work, but the directional movement doesn't seem to register.

**Comment by Calorion** [comment]
> The best stable build from [alunbestor#76](https://github.com/alunbestor/Boxer/issues/76) would probably be this version https://www.dropbox.com/s/nwvw2q9kwxxbd2l/maddsv2%2012.07.2019.zip?dl=0

This file is currently nonexistent. Is there a current best option?

**Comment by bstar** [comment]
Now that there is an official Apple Silicon binary, it would be great to also provide an x86 one as well.

**Comment by MaddTheSane** [comment]
The binary in the release tab is also an Intel binary.

**Comment by bstar** [comment]
@MaddTheSane When I try to run the binary it says that it's damaged and should be moved to trash.  I tried the right click and 'open' process too.
![Screen Shot 2021-01-07 at 4 56 36 PM](https://user-images.githubusercontent.com/92905/103949485-535b9b00-5109-11eb-9378-1e384cb1ff1c.png)
Running Big Sur

**Comment by fedekrum** [comment]
Looks like if you want to be at the edge you must look for them at
[https://boxer.thec0de.com/](https://boxer.thec0de.com/)
