### ISSUE TITLE
Game installers fail to start

### ISSUE THREAD

**Issue by kyods** [MaddTheSane/Boxer#30]
When importing the game into Boxer, the application offers to run the installer - however this option always fails with the following message:

![Screenshot 2021-06-16 at 18 44 17](https://user-images.githubusercontent.com/66119492/122417840-13d38d80-cf8a-11eb-964c-067fc371ec9e.png)

This makes the CD versions impossible to play in Boxer, as they need to be installed first.

**Comment by ajmas** [comment]
What format are the games in (iso, zip, etc)? And what version of Boxer on what version of macOS?

Also does  the latest beta change anything in behaviour for you?

**Comment by kyods** [comment]
Big Sur then, currently Monterey 12.0.1 on a M1 Mac mini. Boxer built from the source available back then in June.

In the current beta 3 the "Session is not ready" message is gone and the game does get imported, however running the installer returns this:

![Screenshot 2021-12-11 at 8 53 03](https://user-images.githubusercontent.com/66119492/145669150-5de1822d-9bfb-4ca8-96bf-816260b7589b.png)

Happens whenever any game installer tries to obtain access to the C: drive. Tested games in the ISO format and with unpacked .exe installers. Possibly related to [#25](https://github.com/MaddTheSane/Boxer/issues/25)?

**Comment by MaddTheSane** [comment]
More than likely, yes.

**Comment by kyods** [comment]
Confirmed fixed in the most recent version.
