### ISSUE TITLE
[Audio] Issue with Roland CM-32 emulation

### ISSUE THREAD

**Issue by shinra-electric** [MaddTheSane/Boxer#37]
This may be a setting issue, but I can't seem to get the Roland sound to work. 

I have the Roland roms in the Application Support folder. 

![Screenshot 2021-12-10 at 12 09 55](https://user-images.githubusercontent.com/50119606/145572291-602e7212-b935-4ed3-96ab-64580f519f8e.png)

In games I tested where I can choose which sound system to use, internal speakers work (but make my ears bleed), but the Roland CM-32 option is just silent.

**Comment by shinra-electric** [comment]
I'm also getting a freeze sometimes when the setup.exe tries to save the settings. I got a few console messages that may or may not be related: 

>[app<application.net.washboardabs.boxer.3741831.3741840(501)>:80948] Ignoring jetsam update because this process is not memory-managed

>[app<application.net.washboardabs.boxer.3741831.3741840(501)>:80948] Ignoring suspend because this process is not lifecycle managed

>[app<application.net.washboardabs.boxer.3741831.3741840(501)>:80948] Set darwin role to: UserInteractiveNonFocal

>[app<application.net.washboardabs.boxer.3741831.3741840(501)>:80948] Ignoring GPU update because this process is not GPU managed

**Comment by ajmas** [comment]
Did you ever have this issue with other apps and if so, how did you resolve it? Not saying it will solve this one, but just trying to compare notes.

**Comment by shinra-electric** [comment]
You mean different dos games? Yes, I had sound issues with three so far.

I'm making new Boxer packages (if that's the right term) from my old Intel ones. 

The only one I had no issues with used internal speakers only.

**Comment by ajmas** [comment]
I mean with different applications, outside of Boxer.

Also, does anything here help: https://www.gog.com/forum/red_baron_pack/getting_the_roland_mt32_sound_emulator_working_with_red_baron - I appreciate it is for a different program, but again maybe similar resolutions steps?

**Comment by kcgen** [comment]
Removing one variable: mt32 confirmed good on "bare" DOSBox Staging, without the Boxer additions,  on macOS  M1 and  x86-64 (11.6.1).
Hopefully this helps isolate where the issue is! 
Thanks to @grounded0 for the test results.

**Comment by ajmas** [comment]
Searching for "DOSBox mt32" gave me this, which may be relevant:

https://github.com/joncampbell123/dosbox-x/issues/2056

**Comment by shinra-electric** [comment]
This seems to have been fixed with the recent 4.1 beta.
