### ISSUE TITLE
4.1 Beta spams requests to control computer using accessibility features

### ISSUE THREAD

**Issue by shinra-electric** [MaddTheSane/Boxer#44]
On opening the 4.1 beta, it requests permission to control the computer using accessibility features. 

I go to system preferences and allow it, and restart Boxer. 

But the permission window keeps coming back many times no matter which option I select. 
![Screenshot 2022-05-01 at 14 41 18](https://user-images.githubusercontent.com/50119606/166148639-fae0cae2-e0a7-4284-bf7b-b3a6a5533ca4.png)

Edit: On Monterey 12.3.1 and M1.

**Comment by dmcondolora** [comment]
I'm having the same problem on macOS Monterey 12.1 and a 2021 MacBook Pro with M1 Pro chip.

**Comment by designbyadrian** [comment]
Monterey 12.5 m1 Pro

**Comment by bfinlay** [comment]
Had the same problem on Intel iMac.

I had the older version from the main homepage installed first and had already given it permissions.   Then I installed the "4.1 beta" tagged version and got the accessibility spamming.

Workaround that worked for me was to use the "-" button to remove boxer from the accessibility options in system preferences (see screenshot in OP above) then restart boxer, open system prefs, and approve.   That has ended the spamming.

**Comment by shinra-electric** [comment]
This seems to have been a macOS issue. I upgraded to Ventura and I don't see the issue anymore.

**Comment by JoshHrach** [comment]
This seems to have returned in macOS 13.1.
