### ISSUE TITLE
Accessibly request repeatedly appears

### ISSUE THREAD

**Issue by JoshHrach** [MaddTheSane/Boxer#48]
When launching Boxer, an accessibility request continually pops up.

> "Boxer" would like to control this computer using accessibility features.

Even with Accessibility enabled for Boxer, this will not go away. 

Affected version: Apple Silicon beta 4.1
MacOS version: 13.1 Ventura

**Comment by ajschot** [comment]
same issue here after a clean install of Ventura I have this issue too

**Comment by ajschot** [comment]
I found the solution:
1) Quit Boxer
2) remove it from the accessibility (not switch it off but really select and press the minus icon)
3) then start boxer
4) accept it accessibility in your system settings

Pop-ups are gone

**Comment by JoshHrach** [comment]
That did it. Thanks!
