### ISSUE TITLE
Problem Compiling on Monterey 12.7.2 and XCode 14.2

### ISSUE THREAD

**Issue by JesseDyer** [MaddTheSane/Boxer#60]
On building, I get: 

```
[redacted]Boxer/Boxer.xcodeproj: This Copy Files build phase contains a reference to a missing file 'OpenEmuShaders.framework'.
[redacted]Boxer/Boxer.xcodeproj: This Copy Files build phase contains a reference to a missing file 'DDHidLib.framework'.
[redacted]Boxer/Boxer.xcodeproj: This Copy Files build phase contains a reference to a missing file 'MT32Emu.framework'.
```

I've pulled the Git project down, and run the `git submodule update --init --recursive` command successfully.  Am I missing something?

**Comment by MaddTheSane** [comment]
Did you open Boxer.xcodeproj or Boxer.xcworkspace?

**Comment by JesseDyer** [comment]
Ha! Thank you, I opened the former.  I opened the latter and reran.  I get significantly farther, but I still fail with:



`[redacted]Boxer/Other Sources/MCAdditions/NSBezierPath+MCAdditions.m:102:18: Property 'CGPath' not found on object of type 'NSBezierPath *'`
`[redacted]Boxer/Other Sources/MCAdditions/NSBezierPath+MCAdditions.m:119:31: No known class method for selector 'bezierPathWithCGPath:'`

**Comment by MaddTheSane** [comment]
What SDK/Xcode version are you using?

**Comment by JesseDyer** [comment]
14.2 (14C18)

**Comment by MaddTheSane** [comment]
Ah.

Fix should be coming soon.

**Comment by MaddTheSane** [comment]
Are you still having issues?

**Comment by JesseDyer** [comment]
The compile works!  Thank you for your fast response!  I do have one more issue, though.  At the end of the process, I find that Boxer Standalone and Boxer Bundler are built, but Boxer itself is not.  Could you tell me what I'm missing?

**Comment by JesseDyer** [comment]
Never mind, I figured that out.  Thank you, once again.
